apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.admin.service.name }}
  labels:
    app: admin
spec:
  type: {{ .Values.admin.service.type }}
  selector:
    app: admin
  ports:
    - name: http
      port: {{ .Values.admin.service.port }}
      targetPort: {{ .Values.admin.service.targetPort }}
      protocol: TCP
