apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend

  labels:
    app: backend

spec:
  replicas: {{ .Values.backend.replicaCount }}

  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}

  strategy:
    type: {{ .Values.strategy.type }}
    rollingUpdate:
      maxUnavailable: {{ .Values.strategy.rollingUpdate.maxUnavailable }}
      maxSurge: {{ .Values.strategy.rollingUpdate.maxSurge }}

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}

      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

    spec:

      serviceAccountName: {{ .Values.backend.serviceAccount.name }}

      automountServiceAccountToken: {{ .Values.backend.serviceAccount.automount }}

      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}

      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}

      containers:
        - name: backend

          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"

          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}

          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}

          ports:
            - name: http
              containerPort: {{ .Values.backend.service.targetPort }}
              protocol: TCP

          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secret

          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}

          livenessProbe:
            {{- toYaml .Values.backend.livenessProbe | nindent 12 }}

          readinessProbe:
            {{- toYaml .Values.backend.readinessProbe | nindent 12 }}

          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}

      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
