{{- if .Values.backend.serviceAccount.create }}

apiVersion: v1
kind: ServiceAccount

metadata:
  name: {{ .Values.backend.serviceAccount.name }}

  {{- with .Values.backend.serviceAccount.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
  {{- end }}

automountServiceAccountToken: {{ .Values.backend.serviceAccount.automount }}

{{- end }}
