apiVersion: v1
kind: Secret

metadata:
  name: backend-secret

type: Opaque

stringData:

  MONGODB_URI: {{ .Values.backend.secret.MONGODB_URI | quote }}

  REDIS_URL: {{ .Values.backend.secret.REDIS_URL | quote }}
