{{- if .Values.backend.secret }}

apiVersion: v1
kind: Secret

metadata:
  name: backend-secret

type: Opaque

stringData:
{{- range $key, $value := .Values.backend.secret }}
  {{ $key }}: {{ $value | quote }}
{{- end }}

{{- end }}
