apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: wanderlust
  labels:
    app: backend

spec:
  replicas: 1

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:

      nodeSelector:
        role: wanderlust

      tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "wanderlust"
        effect: "NoSchedule"

      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: role
                operator: In
                values:
                - wanderlust
      containers:
      - name: backend

        image: rajeshkosta/wanderlust-backend:latest
        imagePullPolicy: Always

        ports:
        - containerPort: 5000

        envFrom:
        - configMapRef:
            name: wanderlust-env
        - secretRef:
            name: wanderlust-secret

        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"

          limits:
            cpu: "500m"
            memory: "512Mi"

        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5

        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: wanderlust

spec:
  type: ClusterIP

  selector:
    app: backend

  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
