# ------------------------------------------------------------------------------
# Global Configuration
# ------------------------------------------------------------------------------
nameOverride: ""
fullnameOverride: ""

imagePullSecrets: []

# ------------------------------------------------------------------------------
# Frontend Configuration
# ------------------------------------------------------------------------------
frontend:

  replicaCount: 2

  image:
    repository: rajeshkosta/wanderlust-frontend
    tag: latest
    pullPolicy: Always

  service:
    name: frontend-svc
    type: ClusterIP
    port: 80
    targetPort: 80


  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

  livenessProbe:
    httpGet:
      path: /
      port: 80
    initialDelaySeconds: 20
    periodSeconds: 10

  readinessProbe:
    httpGet:
      path: /
      port: 80
    initialDelaySeconds: 5
    periodSeconds: 5


# ------------------------------------------------------------------------------
# Backend Configuration
# ------------------------------------------------------------------------------
backend:

  replicaCount: 2

  image:
    repository: rajeshkosta/wanderlust-backend
    tag: latest
    pullPolicy: Always

  serviceAccount:
    create: true
    name: backend-sa

  service:
    name: backend-svc
    type: ClusterIP
    port: 80
    targetPort: 5000


  config:
    NODE_ENV: production
    PORT: "5000"
    APP_NAME: tta-backend
    API_VERSION: v1
    LOG_LEVEL: debug

  secret:
    MONGODB_URI: mongodb://admin:admin123@mongodb.mongodb.svc.cluster.local:27017/wanderlust?authSource=admin
    REDIS_URL: redis://redisdb-master.redisdb.svc.cluster.local:6379
    JWT_SECRET: mySuperSecretKey

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

  livenessProbe:
    httpGet:
      path: /
      port: 5000
    initialDelaySeconds: 20
    periodSeconds: 10

  readinessProbe:
    httpGet:
      path: /
      port: 5000
    initialDelaySeconds: 5
    periodSeconds: 5



# ------------------------------------------------------------------------------
# Admin Configuration
# ------------------------------------------------------------------------------
admin:
  replicaCount: 2

  image:
    repository: rajeshkosta/three-tier-app-admin
    tag: latest
    pullPolicy: Always

  service:
    name: admin-svc
    type: ClusterIP
    port: 80
    targetPort: 80

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

  livenessProbe:
    httpGet:
      path: /
      port: 80
    initialDelaySeconds: 20
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /
      port: 80
    initialDelaySeconds: 5
    periodSeconds: 5

# ------------------------------------------------------------------------------
# Horizontal Pod Autoscaling
# ------------------------------------------------------------------------------
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 20
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80



# ------------------------------------------------------------------------------
# Ingress
# Single Domain
# tta.local
#
# frontend -> /
# backend  -> /api
# admin    -> /admin
# ------------------------------------------------------------------------------

ingress:
  enabled: true
  className: nginx
  annotations: {}
  host: stage.wanderlust.local
  paths:
    frontend:
      path: /
      service: frontend-svc
      port: 80

    backend:
      path: /api
      service: backend-svc
      port: 80

    admin:
      path: /admin
      service: admin-svc
      port: 80

# ------------------------------------------------------------------------------
# Scheduling
# ------------------------------------------------------------------------------

nodeSelector: {}

tolerations:
  - key: workload
    operator: Equal
    value: application
    effect: NoSchedule

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: workload
              operator: In
              values:
                - application
# ------------------------------------------------------------------------------
# Deployment Strategy
# ------------------------------------------------------------------------------

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 25%
    maxSurge: 25%
revisionHistoryLimit: 5
terminationGracePeriodSeconds: 30
