apiVersion: v1
kind: Secret
metadata:
  name: wanderlust-secret
  namespace: wanderlust

type: Opaque

stringData:

  # MongoDB
  MONGODB_URI: "mongodb://root:Ramleela01234@mongo.database.svc.cluster.local:27017/wanderlust?authSource=admin"

  REDIS_URL: "redis://redis.database.svc.cluster.local:6379"

  # JWT
  JWT_SECRET: "super-secret-jwt-key"

  # Session
  SESSION_SECRET: "super-secret-session-key"

  # Optional External APIs
  CLOUDINARY_API_KEY: "your-cloudinary-key"

  CLOUDINARY_SECRET: "your-cloudinary-secret"

  EMAIL_USER: "your-email@gmail.com"

  EMAIL_PASS: "your-email-password"
