apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: mongo-pvc
  namespace: database

spec:
  accessModes:
    - ReadWriteOnce

  storageClassName: manual

  resources:
    requests:
      storage: 5Gi
