apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: wanderlust-ingress

  labels:
    {{- include "frontend.labels" . | nindent 4 }}

spec:
  ingressClassName: {{ .Values.ingress.className }}

  rules:
    - host: {{ .Values.ingress.host }}

      http:
        paths:

          # Frontend
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-svc
                port:
                  number: 80
          # Backend API
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend-svc
                port:
                  number: 80
